---
# vars file for deploy_app

- name: Adding volume for mongodb config
  ansible.builtin.file:
    path: /opt/apps/mongodb/configdb
    mode: "0644"
    state: directory
    owner: root
    group: root

- name: Adding volume for mongodb data
  ansible.builtin.file:
    path: /opt/apps/mongodb/db
    mode: "0644"
    state: directory
    owner: root
    group: root

- name: Run New Image
  community.docker.docker_compose_v2:
    project_src: docker-compose.yaml
    project_name: todos
    state: present
    pull: missing

  register: app_deployment_result

- name: App deployment
  ansible.builtin.debug:
    var: app_deployment_result
